version: '3.8'
services:
  web:
    build: .
    command: bash -c "python init_db.py &&
                      alembic -x db_env=master_db upgrade head && 
                      alembic -x db_env=test_db upgrade head && 
                      uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_ADDRESS=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=xops_test
      - TEST_DB_NAME=test_db
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env


volumes:
  postgres_data:
